name: CI/CD main branch -> 30.georgebrata.ro
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build

      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.30.georgebrata.ro
          username: deploy@30.georgebrata.ro
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./dist/
